alias ls='pwd && exa --classify --header --all --git --long'
alias ll='pwd && exa --classify --header --all --git --long'
alias la='pwd && exa --classify --header --all --git --long --sort date --reverse'
alias c='clear'
alias cl='c && ll'
alias ca='c && la'
alias l='ls'

alias whence='type -a'
alias less='less -r'
alias grep='grep --color'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias df='df -h'
alias du='ncdu'
alias tree='exa --tree'
alias tg='tree | grep '
alias pst='pstree -u $USER'
alias psg='pst | grep '

alias cg='clear && git status'
alias ga='git add'
alias gau='git add --update'
alias gb='git branch'
alias gbd='git branch --delete '
alias gc='git commit'
alias gcm='git commit --message'
# marks and prefixes comment as fix-up. combine
# with `gr -i --autosquash <last commit to retain>` to merge (rebase) fixups
alias gcf='git commit --fixup'
alias gca='git commit --amend'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcom='git checkout master'
alias gcon='git checkout next'
alias gcod='git checkout dev'
alias gd='git diff'
alias gda='git diff HEAD'
alias gi='git init'
alias glg='git log --graph --oneline --decorate --all'
alias gld='git log --pretty=format:"%h %ad %s" --date=short --all'
alias gm='git merge'
alias gma='git merge --abort'
alias gmc='git merge --continue'
alias gp='git pull'
alias gpr='git pull --rebase'
alias gr='git rebase'
alias gres='git reset'
alias gresh='git reset HEAD'
alias grs='git restore'
alias grss='git restore --staged'
alias gs='git status'
alias gss='git status --short'
alias gst='git stash'
alias gsta='git stash apply'
alias gstd='git stash drop'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gsts='git stash save'

alias church='autossh -M 0 {$SSHUSER}@church.csce.uark.edu'
alias turing='autossh -M 0 {$SSHUSER}@turing.csce.uark.edu'

alias ambnet='ssh -i "/home/fowl/.keys/amb-staging.pem" ec2-user@ec2-3-233-61-225.compute-1.amazonaws.com'
alias ambstaging='ssh -i "/home/fowl/.keys/amb-staging.pem" ec2-user@ec2-3-209-241-43.compute-1.amazonaws.com'
alias ambui='ssh -i "/home/fowl/.keys/amb-staging.pem" ec2-user@ec2-3-211-160-0.compute-1.amazonaws.com'

alias g++='g++ -std=c++11 -Wall'
alias livestreamer='livestreamer --http-header=Client-ID=jzkbprff40iqj646a697cyrvl0zt2m6'
alias djangodev='source ~/.virtualenvs/djangodev/bin/activate'

alias dm='docker-machine'
alias dps='docker ps -a'
alias dsra='docker stop $(docker ps -aq) && docker rm $(docker ps -aq)'
alias dbu='docker-compose build && docker-compose up -d'
alias drmi='docker rmi $(docker images -a --filter=dangling=true -q) && docker rm $(docker ps --filter=status=exited --filter=status=created -q)'
